version: 2.1

configure: &configure
  docker:
    - image: cimg/base:2021.04
  resource_class: small

release: &release
  run:
    name: Create release
    command: ./scripts/release.sh
    no_output_timeout: 60m

filters: &filters
  filters:
    branches: {}

jobs:
  release:
    <<: *configure
    steps:
    - checkout
    - setup_remote_docker
    - *release
  release-publish:
    <<: *configure
    steps:
    - checkout
    - setup_remote_docker
    - *release
    - run:
        name: Login docker
        command: echo -e "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
    - run:
        name: Push docker image
        command: docker push "$(docker images heathmont/docker-proxy --format "{{.Repository}}:{{.Tag}}" | head -n 2 | tail -1)"

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          <<: *filters
          cron: "0 5 * * *"  # 05:00 UTC
    jobs:
      - release:
          <<: *filters
          context: global
  push:
    jobs:
      - release-publish:
          <<: *filters
          context: global